theme: jekyll-theme-cayman
title: Raffaele Sorrentino
name: Raffaele Sorrentino
description: Hello world! I'm Raffaele, born in 1997, based in Naples (Italy), and this is my personal website!

lsi: false
safe: true
source: sorrentinoraf.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
site:
  github:
    is_project_page: false
